import jsPDF from 'jspdf';
import { 
  Molecule, 
  QuantumDescriptor, 
  ADMETProperty, 
  DrugLikenessResult,
  PDFExportConfig,
  DescriptorCategory,
  ADMETCategory,
} from '../types';

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function addHeader(doc: jsPDF, molecule: Molecule, pageNum: number, totalPages: number) {
  doc.setFillColor(10, 22, 40);
  doc.rect(0, 0, PAGE_WIDTH, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Molecular Property Report', MARGIN, 16);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Molecule: ${molecule.name}`, MARGIN, 22);
  
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN - 25, 22, { align: 'right' });
}

function addFooter(doc: jsPDF, date: Date) {
  doc.setFillColor(240, 240, 240);
  doc.rect(0, PAGE_HEIGHT - 12, PAGE_WIDTH, 12, 'F');
  
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated by Molecular Property Calculator on ${date.toLocaleDateString()} ${date.toLocaleTimeString()}`,
    MARGIN,
    PAGE_HEIGHT - 4
  );
}

function addSectionHeader(doc: jsPDF, title: string, color: [number, number, number], y: number): number {
  doc.setFillColor(color[0], color[1], color[2]);
  doc.rect(MARGIN, y, CONTENT_WIDTH, 8, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN + 3, y + 6);
  
  return y + 12;
}

function addMoleculeInfo(doc: jsPDF, molecule: Molecule, y: number): number {
  y = addSectionHeader(doc, 'Molecule Information', [59, 130, 246], y);
  
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const elementCounts: Record<string, number> = {};
  molecule.atoms.forEach(atom => {
    elementCounts[atom.element] = (elementCounts[atom.element] || 0) + 1;
  });
  
  const formula = Object.keys(elementCounts)
    .sort((a, b) => {
      if (a === 'C') return -1;
      if (b === 'C') return 1;
      if (a === 'H') return -1;
      if (b === 'H') return 1;
      return a.localeCompare(b);
    })
    .map(el => elementCounts[el] === 1 ? el : `${el}${elementCounts[el]}`)
    .join('');
  
  const info = [
    { label: 'Name', value: molecule.name },
    { label: 'Formula', value: formula },
    { label: 'Type', value: molecule.type },
    { label: 'Atoms', value: molecule.atoms.length.toString() },
    { label: 'Bonds', value: molecule.bonds.length.toString() },
    { label: 'Description', value: molecule.description || 'N/A' },
  ];
  
  info.forEach((item, i) => {
    const currentY = y + i * 7;
    doc.setFont('helvetica', 'bold');
    doc.text(`${item.label}:`, MARGIN, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(item.value, MARGIN + 30, currentY);
  });
  
  return y + info.length * 7 + 8;
}

function addQuantumDescriptors(
  doc: jsPDF, 
  descriptors: QuantumDescriptor[], 
  y: number,
  addNewPage: () => number
): number {
  const descriptorCategories: Record<DescriptorCategory, { label: string; color: [number, number, number] }> = {
    electronic: { label: 'Electronic', color: [139, 92, 246] },
    structural: { label: 'Structural', color: [59, 130, 246] },
    topological: { label: 'Topological', color: [16, 185, 129] },
    physicochemical: { label: 'Physicochemical', color: [245, 158, 11] },
  };

  y = addSectionHeader(doc, 'Quantum Chemical Descriptors', [59, 130, 246], y);
  
  const grouped = descriptors.reduce((acc, d) => {
    if (!acc[d.category]) acc[d.category] = [];
    acc[d.category].push(d);
    return acc;
  }, {} as Record<DescriptorCategory, QuantumDescriptor[]>);
  
  (Object.keys(descriptorCategories) as DescriptorCategory[]).forEach((category) => {
    const categoryData = descriptorCategories[category];
    const categoryDescriptors = grouped[category];
    
    if (!categoryDescriptors || categoryDescriptors.length === 0) return;
    
    if (y > PAGE_HEIGHT - 50) {
      y = addNewPage();
    }
    
    doc.setFillColor(categoryData.color[0], categoryData.color[1], categoryData.color[2]);
    doc.rect(MARGIN, y, 3, 6, 'F');
    
    doc.setTextColor(categoryData.color[0], categoryData.color[1], categoryData.color[2]);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(categoryData.label, MARGIN + 5, y + 5);
    
    y += 10;
    
    const colWidth = CONTENT_WIDTH / 2;
    
    categoryDescriptors.forEach((descriptor, idx) => {
      if (y > PAGE_HEIGHT - 30) {
        y = addNewPage();
      }
      
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      const x = MARGIN + col * colWidth;
      const rowY = y + row * 7;
      
      doc.setTextColor(80, 80, 80);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(descriptor.name, x, rowY);
      
      doc.setTextColor(20, 20, 20);
      doc.setFont('helvetica', 'bold');
      const value = Math.abs(descriptor.value) >= 1000 || Math.abs(descriptor.value) < 0.01 && descriptor.value !== 0
        ? descriptor.value.toExponential(2)
        : descriptor.value.toFixed(2);
      doc.text(`${value} ${descriptor.unit || ''}`, x + colWidth - 25, rowY, { align: 'right' });
    });
    
    y += Math.ceil(categoryDescriptors.length / 2) * 7 + 5;
  });
  
  return y + 5;
}

function addADMETProperties(
  doc: jsPDF, 
  properties: ADMETProperty[], 
  y: number,
  addNewPage: () => number
): number {
  const admetCategories: Record<ADMETCategory, { label: string; color: [number, number, number] }> = {
    absorption: { label: 'Absorption', color: [16, 185, 129] },
    distribution: { label: 'Distribution', color: [59, 130, 246] },
    metabolism: { label: 'Metabolism', color: [245, 158, 11] },
    excretion: { label: 'Excretion', color: [139, 92, 246] },
    toxicity: { label: 'Toxicity', color: [239, 68, 68] },
  };

  y = addSectionHeader(doc, 'ADMET Property Prediction', [16, 185, 129], y);
  
  const grouped = properties.reduce((acc, p) => {
    if (!acc[p.category]) acc[p.category] = [];
    acc[p.category].push(p);
    return acc;
  }, {} as Record<ADMETCategory, ADMETProperty[]>);
  
  (Object.keys(admetCategories) as ADMETCategory[]).forEach((category) => {
    const categoryData = admetCategories[category];
    const categoryProps = grouped[category];
    
    if (!categoryProps || categoryProps.length === 0) return;
    
    if (y > PAGE_HEIGHT - 50) {
      y = addNewPage();
    }
    
    doc.setFillColor(categoryData.color[0], categoryData.color[1], categoryData.color[2]);
    doc.rect(MARGIN, y, 3, 6, 'F');
    
    doc.setTextColor(categoryData.color[0], categoryData.color[1], categoryData.color[2]);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(categoryData.label, MARGIN + 5, y + 5);
    
    y += 10;
    
    categoryProps.forEach((prop, idx) => {
      if (y > PAGE_HEIGHT - 40) {
        y = addNewPage();
      }
      
      const statusColor: Record<string, [number, number, number]> = {
        good: [16, 185, 129],
        moderate: [245, 158, 11],
        poor: [239, 68, 68],
        unknown: [100, 100, 100],
      };
      
      const color = statusColor[prop.status] || statusColor.unknown;
      const statusLabel = prop.status.charAt(0).toUpperCase() + prop.status.slice(1);
      
      doc.setFillColor(color[0], color[1], color[2]);
      doc.roundedRect(MARGIN, y - 4, CONTENT_WIDTH, 24, 2, 2, 'F');
      
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(MARGIN + 2, y - 2, CONTENT_WIDTH - 4, 20, 1, 1, 'F');
      
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(prop.name, MARGIN + 5, y + 3);
      
      doc.setTextColor(color[0], color[1], color[2]);
      doc.setFontSize(9);
      doc.text(`[${statusLabel}]`, MARGIN + 5, y + 12);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      doc.text(prop.prediction, MARGIN + 30, y + 12);
      
      doc.setTextColor(30, 30, 30);
      doc.setFont('helvetica', 'bold');
      doc.text(`${Math.round(prop.probability * 100)}%`, MARGIN + CONTENT_WIDTH - 15, y + 8, { align: 'right' });
      
      y += 26;
    });
    
    y += 4;
  });
  
  return y + 5;
}

function addDrugLikeness(
  doc: jsPDF, 
  result: DrugLikenessResult, 
  y: number,
  addNewPage: () => number
): number {
  y = addSectionHeader(doc, 'Drug-Likeness Assessment', [139, 92, 246], y);
  
  const getScoreColor = (score: number): [number, number, number] => {
    if (score >= 80) return [16, 185, 129];
    if (score >= 60) return [245, 158, 11];
    if (score >= 40) return [249, 115, 22];
    return [239, 68, 68];
  };
  
  const overallColor = getScoreColor(result.overallScore);
  
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 35, 3, 3, 'F');
  
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Score', MARGIN + 5, y + 12);
  
  doc.setFontSize(24);
  doc.setTextColor(overallColor[0], overallColor[1], overallColor[2]);
  doc.text(`${result.overallScore}/100`, MARGIN + 5, y + 30);
  
  const barWidth = CONTENT_WIDTH - 60;
  const barHeight = 8;
  const barX = MARGIN + 55;
  const barY = y + 22;
  
  doc.setFillColor(220, 220, 220);
  doc.roundedRect(barX, barY, barWidth, barHeight, 2, 2, 'F');
  
  doc.setFillColor(overallColor[0], overallColor[1], overallColor[2]);
  doc.roundedRect(barX, barY, barWidth * (result.overallScore / 100), barHeight, 2, 2, 'F');
  
  y += 42;
  
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(result.summary, MARGIN, y);
  
  y += 12;
  
  result.rules.forEach((rule, idx) => {
    if (y > PAGE_HEIGHT - 40) {
      y = addNewPage();
    }
    
    const ruleColor = rule.passed ? [16, 185, 129] : [239, 68, 68];
    
    doc.setFillColor(rule.passed ? 240 : 255, rule.passed ? 250 : 240, rule.passed ? 240 : 240);
    doc.roundedRect(MARGIN, y - 4, CONTENT_WIDTH, 28, 2, 2, 'F');
    
    doc.setFillColor(ruleColor[0], ruleColor[1], ruleColor[2]);
    doc.rect(MARGIN, y - 4, 3, 28, 'F');
    
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(rule.ruleName, MARGIN + 8, y + 3);
    
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(rule.details, MARGIN + 8, y + 13);
    
    if (rule.threshold) {
      doc.setTextColor(120, 120, 120);
      doc.setFontSize(8);
      doc.text(`Threshold: ${rule.threshold}`, MARGIN + 8, y + 20);
    }
    
    doc.setTextColor(ruleColor[0], ruleColor[1], ruleColor[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${rule.score}`, MARGIN + CONTENT_WIDTH - 20, y + 10, { align: 'right' });
    
    const barX = MARGIN + CONTENT_WIDTH - 70;
    const barWidth = 45;
    const barHeight = 4;
    const barY = y + 16;
    
    doc.setFillColor(220, 220, 220);
    doc.roundedRect(barX, barY, barWidth, barHeight, 1, 1, 'F');
    
    doc.setFillColor(ruleColor[0], ruleColor[1], ruleColor[2]);
    doc.roundedRect(barX, barY, barWidth * (rule.score / 100), barHeight, 1, 1, 'F');
    
    y += 30;
  });
  
  return y + 5;
}

export async function exportPropertyReport(
  molecule: Molecule,
  quantumDescriptors: QuantumDescriptor[] | null,
  admetProperties: ADMETProperty[] | null,
  drugLikeness: DrugLikenessResult | null,
  config: PDFExportConfig
): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: config.pageSize || 'a4',
  });
  
  const date = new Date();
  let currentPage = 1;
  let totalPages = 1;
  
  const addNewPage = () => {
    totalPages++;
    doc.addPage();
    currentPage = totalPages;
    addHeader(doc, molecule, currentPage, totalPages);
    return 30;
  };
  
  totalPages = 1;
  let estimateY = 30;
  
  if (config.includeMoleculeInfo) {
    estimateY += 50;
  }
  if (config.includeQuantum && quantumDescriptors) {
    estimateY += 150;
    if (estimateY > PAGE_HEIGHT - 30) {
      totalPages++;
      estimateY = 30 + 150;
    }
  }
  if (config.includeADMET && admetProperties) {
    estimateY += 200;
    if (estimateY > PAGE_HEIGHT - 30) {
      totalPages++;
      estimateY = 30 + 200;
    }
  }
  if (config.includeDrugLikeness && drugLikeness) {
    estimateY += 180;
    if (estimateY > PAGE_HEIGHT - 30) {
      totalPages++;
    }
  }
  
  currentPage = 1;
  addHeader(doc, molecule, 1, totalPages);
  let y = 30;
  
  if (config.includeMoleculeInfo) {
    y = addMoleculeInfo(doc, molecule, y);
  }
  
  if (config.includeQuantum && quantumDescriptors) {
    if (y > PAGE_HEIGHT - 50) {
      y = addNewPage();
    }
    y = addQuantumDescriptors(doc, quantumDescriptors, y, addNewPage);
  }
  
  if (config.includeADMET && admetProperties) {
    if (y > PAGE_HEIGHT - 50) {
      y = addNewPage();
    }
    y = addADMETProperties(doc, admetProperties, y, addNewPage);
  }
  
  if (config.includeDrugLikeness && drugLikeness) {
    if (y > PAGE_HEIGHT - 50) {
      y = addNewPage();
    }
    y = addDrugLikeness(doc, drugLikeness, y, addNewPage);
  }
  
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, date);
  }
  
  const fileName = `${molecule.name.replace(/\s+/g, '_')}_property_report.pdf`;
  doc.save(fileName);
}
